name: CI_pipeline

on:
    push:

jobs:
    ci-pipeline:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12.11
        
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            
        - name: Format
          run:
            black main.py
        
        - name: Lint
          run:
            flake8 main.py
        
        - name: Test
          run:
            pytest tests.py