name: CI_pipeline

on:
    push:
      branches: [ "dev" ]

jobs:
    ci-pipeline:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12.11-slim
        
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            
        - name: Format
          run: black main.py
        
        - name: Lint
          run: flake8 main.py
        
        - name: Test
          run: pytest tests.py

        - name: Commit and push formatted code to master branch
          run: |
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git checkout -b master
            git add .
            git commit -m "Auto format code" || echo "No changes to commit"
            git push origin master --force
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}